#pragma once

namespace esphome {
namespace gatepro {

enum GateProCmd : uint8_t {
   GATEPRO_CMD_NONE,
   GATEPRO_CMD_OPEN,
   GATEPRO_CMD_CLOSE,
   GATEPRO_CMD_STOP,
   GATEPRO_CMD_READ_STATUS,
   GATEPRO_CMD_READ_PARAMS,
   GATEPRO_CMD_WRITE_PARAMS,
   GATEPRO_CMD_LEARN,
   GATEPRO_CMD_DEVINFO,
   GATEPRO_CMD_READ_LEARN_STATUS,
   GATEPRO_CMD_REMOTE_LEARN,
   GATEPRO_CMD_CLEAR_REMOTE_LEARN, // untested
   GATEPRO_CMD_RESTORE, // untested
   GATEPRO_CMD_PED_OPEN, // untested
   GATEPRO_CMD_READ_FUNCTION, // untested
};  

const std::map<GateProCmd, const char*> GateProCmdMapping = {
   {GATEPRO_CMD_NONE, "NAK"},
   {GATEPRO_CMD_OPEN, "FULL OPEN;src=P00287D7"},
   {GATEPRO_CMD_CLOSE, "FULL CLOSE;src=P00287D7"},
   {GATEPRO_CMD_STOP, "STOP;src=P00287D7"},
   {GATEPRO_CMD_READ_STATUS, "RS;src=P00287D7"},
   {GATEPRO_CMD_READ_PARAMS, "RP,1:;src=P00287D7"},
   {GATEPRO_CMD_WRITE_PARAMS, "WP,1:"},
   {GATEPRO_CMD_LEARN, "AUTO LEARN;src=P00287D7"},
   {GATEPRO_CMD_DEVINFO, "READ DEVINFO;src=P00287D7"},
   {GATEPRO_CMD_READ_LEARN_STATUS, "READ LEARN STATUS;src=P00287D7"},
   {GATEPRO_CMD_REMOTE_LEARN, "REMOTE LEARN;src=P00287D7"},
   {GATEPRO_CMD_CLEAR_REMOTE_LEARN, "CLEAR REMOTE LEARN;src=P00287D7"},
   {GATEPRO_CMD_RESTORE, "RESTORE;src=P00287D7"},
   {GATEPRO_CMD_PED_OPEN, "PED OPEN;src=P00287D7"},
   {GATEPRO_CMD_READ_FUNCTION, "READ FUNCTION;src=P00287D7"},
};

}}