web_server:
  version: 3

uart:
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO16

external_components:
  - source: github://markv9401/esphome_external_components@main
    components: [ gatepro ]
    refresh: 0s    

cover:
  - platform: gatepro
    name: "Driveway gate"
    device_class: gate
    update_interval: 0.5s
    opening_dir:
      name: "Opening direction"
    auto_close:
      name: "Auto close"
    operational_speed:
      name: "Operational speed"
    decel_dist:
      name: "Decel. at distance"
    decel_speed:
      name: "Decel. speed target"
    max_amp:
      name: "Max torque"
    ped_dura:
      name: "Pedestr. duration"
    flashing_light:
      name: "Flashing light"
    overload_action:
      name: "Torque overload action"
    remote_btn_open:
      name: "Remote btn.: open"
    remote_btn_ped:
      name: "Remote btn.: pedestr."
    remote_btn_extdev:
      name: "Remote btn.: external dev."
    infra1:
      name: "Infra-gate 1"
    infra2:
      name: "Infra-gate 2"
    stop_terminal:
      name: "Stop terminal fn"
    op_method:
      name: "Operational method"
    remote_learn:
      name: "Remote learn"
    ped_open:
      name: "Pedestr. open"
    devinfo:
      name: "Dev. info"
    learn_status:
      name: "Learn status"


button:
  - platform: restart
    name: "Reboot"
    id: reboot_btn
    entity_category: "diagnostic"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB sensor"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: uptime
    type: seconds
    name: "Uptime sensor"
    id: uptime_sensor
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: esphome_version
    entity_category: "diagnostic"
